version: '3.4'

services:

  buber-dinner:
    container_name: buber-dinner
    build:
      context: ./src/
    ports:
      - "8088:80"
    networks:
      - dev
    environment:
      - ConnectionStrings__DefaultConnection=Host=localhost:5432;User ID=postgres;Password=postgres;
      - ASPNETCORE_URLS-http://+:80
    depends_on:
      - "db"
    restart: on-failure

  db:
    image: postgres:latest
    container_name: db
    ports:
      - "5433:5432"
    networks:
      - dev
    environment:
      - POSTGRES_USER-postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=SampleDb
    volumes:
      - app_data:/var/lib/postgresql/data
    restart: always

volumes:
  app_data:


networks:
  dev:
    driver: bridge
