version: '3.4'

services:

  buberdinner.api:
    image: buberdinner.api
    container_name: api
    build:
      context: .
    ports:
      - "5080:80"
    networks:
      - default
    environment:
      - ConnectionStrings__Default=Host=db;User ID=postgres;Password=postgres;
      - JwtSettings__Secret=BuberDinnerSecretKey
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - "db"
    restart: on-failure

  db:
    image: postgres:latest
    container_name: db
    ports:
      - "5433:5432"
    networks:
      - default
    environment:
      - POSTGRES_USER-postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - data:/var/lib/postgresql/data
    restart: always

volumes:
  data:


networks:
  default:
